
version: '2.4'

services:

  ubuntu_agent:
    image: ubuntu-audit:latest
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\filebeat\:/etc/filebeat/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\auditbeat\:/etc/auditbeat/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\:/etc/supervisor/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\agent:/usr/local/bin
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\agent\log:/var/log/agent
    command: ["sh","-c","/usr/bin/supervisord -c /etc/supervisor/supervisor_win.conf"]
    #command: ["sh","-c","chmod go-w /etc/auditbeat/auditbeat_ubuntu.yml && auditbeat -e -c /etc/auditbeat/auditbeat_ubuntu.yml"]
  
  windows_agent:
    platform: windows
    image: winserv3:latest
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\auditbeat\:C:\auditbeat\conf\
    command: powershell expand-archive -Path OpenSSH-Win64.zip ; cd OpenSSH-Win64 ; cd OpenSSH-Win64 ; powershell.exe -ExecutionPolicy Bypass -File install-sshd.ps1 ; net start sshd ; C:\\auditbeat\\auditbeat.exe -e -c C:\\auditbeat\\conf\\auditbeat_win.yml ; expand-archive -Path C:\\winlogbeat.zip ; C:\\winlogbeat\\winlogbeat.exe -e -c C:\\auditbeat\\conf\\winlogbeat.yml 

  logstash:
    #image: ubuntu-logstash-ws:latest
    image: ubuntu-logstash-win6:latest
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\logstash\:/etc/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\logstash\output:/home
    ports: ['3232:3232']
    #command: ["sh","-c","export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 && /usr/share/logstash/bin/logstash -f '/etc/logstash/pipelines/{logstash_auditfile.conf,logstash_process.conf}' && tail -f /dev/null"]
    command: ["sh","-c","export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 && /usr/share/logstash/bin/logstash -f /etc/logstash2.conf && tail -f /dev/null"]

  triplewave:
    image: ubuntu-tw-new3:latest
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\basehost\:/usr/local/bin/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\examples\transform\:/home/triplewave/examples/transform/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\config\:/home/triplewave/config/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\stream\input_stream\:/home/triplewave/stream/input_stream/
    ports: ['8124:8124']
    depends_on:
      - "logstash"
    command: ["sh","-c","sleep 65 && cd /home/triplewave && chmod +x start.sh && ./start.sh"]
    #command: ["sh","-c","tail -f /dev/null"]