version: '2.4'

services:
  agent:
    image: ubuntu-agent-new2:latest
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\filebeat\:/etc/filebeat/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\:/etc/supervisor/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\agent:/usr/local/bin
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\agent\log:/var/log/agent
    command: ["sh","-c","/usr/bin/supervisord -c /etc/supervisor/supervisor_win.conf"]

  logstash:
    #image: ubuntu-logstash-ws:latest
    image: ubuntu-logstash-win6:latest
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\logstash\:/etc/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\logstash\output:/home
    ports: ['3232:3232']
    depends_on:
      - "agent"
    command: ["sh","-c","export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 && /usr/share/logstash/bin/logstash -f /etc/logstash2.conf && tail -f /dev/null"]

  basehost:
    image: ubuntu-host:18.04
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\basehost\:/usr/local/bin/
    command: ["sh","-c","sleep 70 && /usr/local/bin/start.sh && tail -f /dev/null"]
    #command: ["sh","-c","tail -f /dev/null"]

  triplewave:
    image: ubuntu-tw-new:latest
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\basehost\:/usr/local/bin/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\examples\transform:/home/TripleWave/examples/transform
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\config:/home/TripleWave/config
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\stream\input_stream:/home/TripleWave/stream/input_stream
    ports: ['8124:8124']
    depends_on:
      - "logstash"
    command: ["sh","-c","sleep 60 && cd /home/TripleWave && ./start.sh"]

  #winnanoserver:
    #platform: windows
    #image: mcr.microsoft.com/windows/servercore:10.0.17763.615-amd64
    #command: ping localhost -t
   
  virtuoso:
    image: ubuntu-virtuoso-new:latest
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\virtuoso\:/bin/virtuoso/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\:/etc/virtuoso
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://www.example.com/my-graph"
    ports: ['8890:8890','1111:1111']
    depends_on:
      - "triplewave"
    command: ["sh","-c","/usr/bin/supervisord -c /etc/supervisor2_win.conf"]