
version: '2.4'


services:

  triplewave:
    image: ubuntu-tw-new3:latest
    platform: linux
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\basehost\:/usr/local/bin/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\examples\transform\:/home/triplewave/examples/transform/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\config\:/home/triplewave/config/
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles_win\triplewave\stream\input_stream\:/home/triplewave/stream/input_stream/
    ports: ['8124:8124']
    command: ["sh","-c","sleep 65 && cd /home/triplewave && chmod +x start.sh && ./start.sh"]
    #command: ["sh","-c","tail -f /dev/null"]
  
  
