version: '2.4'

services:
  agent:
    image: ubuntu-sepses25:latest
    #image: ubuntu-agent:latest
    privileged: true
    pid: host
    cap_add: ['AUDIT_CONTROL','AUDIT_READ'] 
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles\filebeat\filebeat2.yml:/etc/filebeat2.yml
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles\supervisor.conf:/etc/supervisor.conf
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles\agent:/usr/local/bin
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles\agent\log:/var/log/agent
    networks:
    - ubuntu
    command: ["sh","-c","/usr/bin/supervisord -c /etc/supervisor.conf"]

  logstash:
    #image: ubuntu-logstash-ws:latest
    image: ubuntu-logstash-new:latest
    volumes:
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles\logstash\logstash2.conf:/etc/logstash2.conf
    - D:\GDriveUndip\PhD\FileAccess\dockerfiles\logstash\output:/home
    #ports: ['3232:3232']
    networks:
    - ubuntu
    depends_on:
      - "agent"
    command: ["sh","-c","/usr/share/logstash/bin/logstash -f /etc/logstash2.conf && tail -f /dev/null"]


networks:
  ubuntu:
   driver: bridge
   ipam:
     config:
     - subnet: 172.0.0.0/16